### ISSUE TITLE
[BUG] Module boo/powershell - Namespace 'System.Management.Automation' not found in assembly

### ISSUE THREAD

**Issue by hackabean** [byt3bl33d3r/SILENTTRINITY#105]
Bug in module boo/powershell.  

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

SILENTTRINITY Version: Zuiikin 0.4.0dev
OS running the Client: Arch Linux 
Python Version Running the Client 3.7.4
OS running the TeamServer: Arch Linux 
Python version running the Teamserver: 3.7.4

**Expected Behavior**

Running boo/powershell module should provide command output from running the module

`for eg.
use boo/powershell
set Command whoami
run all`

Expecting to see current logged in username.

**Current Behavior**

No desired output is returned, instead ST errors with:

`Error compiling source:
V8wD083t3g.boo(4,8): BCE0167: Namespace 'System.Management.Automation' not found in assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

**Failure Information**

See the screenshoot for detailed DEBUG information:

![image](https://user-images.githubusercontent.com/50614334/65681290-166cb180-e048-11e9-939f-54a8011beab3.png)

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

`After installing, pipenv, etc etc... Launch the teamserver python3 teamserver.py 192.168.1.175 pass
Connect client c&c to teamserver python3 st.py wss://username:pass@192.168.0.175:5000
Set up a listener: listeners, use https, options, start https
Set up a stager: stagers, use powershell, generate https
Copy stager.ps1 to windows victim machine
Execute the stager: powershell -ep bypass .\stager.ps1
Get a session, set up boo/powershell module and run all.`
...

**Comment by byt3bl33d3r** [comment]
@hackabean Fixed!
Thanks!

**Comment by hackabean** [comment]
Uhmm.. almost:

> 
[1] ST (modules)(boo/powershell)   run all                                                                                                                                                     
[*] [TS-jtuDp] 7d69b187-1f71-4892-bb46-be5ef8b221df returned job result (id: RCzbygNzdQ)
System.ApplicationException: Cannot find assembly: 'System.Management.Automation'
   at Boo.Lang.Compiler.CompilerParameters.LoadAssemblyFromLibPaths(String assembly, Boolean throwOnError)
   at Boo.Lang.Compiler.CompilerParameters.ForName(String assembly, Boolean throwOnError)
   at Boo.Lang.Compiler.CompilerParameters.LoadAssembly(String assemblyName, Boolean throwOnError)
   at STJob.CompileAndRun(String source, List references) in C:\Users\admin\Desktop\Stage.boo:line 515
   at STJob.Start() in C:\Users\admin\Desktop\Stage.boo:line 386

>

**Comment by byt3bl33d3r** [comment]
Weird, works for me. What Windows version is the session running on?

**Comment by hackabean** [comment]
> Host Name:                 DESKTOP-B14DC6N
OS Name:                   Microsoft Windows 10 Enterprise LTSC
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          admin
Registered Organization:
Product ID:                00425-00000-00002-AA195
Original Install Date:     8/12/2019, 4:48:54 AM
System Boot Time:          9/27/2019, 11:36:36 AM
System Manufacturer:       innotek GmbH
System Model:              VirtualBox
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 61 Stepping 4 GenuineIntel ~998 Mhz
BIOS Version:              innotek GmbH VirtualBox, 12/1/2006
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     1,280 MB
Available Physical Memory: 190 MB
Virtual Memory: Max Size:  2,559 MB
Virtual Memory: Available: 736 MB
Virtual Memory: In Use:    1,823 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-B14DC6N
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB4514366
                           [02]: KB4462930
                           [03]: KB4465065
                           [04]: KB4503308
                           [05]: KB4509095
                           [06]: KB4512577
                           [07]: KB4512937
                           [08]: KB4516115
                           [09]: KB4512578
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) PRO/1000 MT Desktop Adapter

>
