### ISSUE TITLE
ModuleNotFoundError:  No module named '_sqlite3'

### ISSUE THREAD

**Issue by chrisandjer949** [byt3bl33d3r/SILENTTRINITY#114]
#Issue Template

## Context

Hi, I am new ST.  Recently watched your Web session.  Trying to install ST.   But I am getting this error below about _sqlite3.   Something wrong on my Kali Linux VM?   Much appreciate your patience!
```
(root) root@kali:~/SILENTTRINITY# python3 teamserver.py 192.168.8.10 test1234
2019-10-05 19:22:57,968 1884 IPCServer - [DEBUG] ipcserver.py: run - Started IPC server on 127.0.0.1:61848
Traceback (most recent call last):
  File "teamserver.py", line 32, in <module>
    from core.teamserver.db import AsyncSTDatabase
  File "/root/SILENTTRINITY/core/teamserver/db.py", line 1, in <module>
    import aiosqlite
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.7/site-packages/aiosqlite/__init__.py", line 6, in <module>
    from sqlite3 import (  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
(root) root@kali:~/SILENTTRINITY# 
```

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* SILENTTRINITY Version:
* OS running the Client:   Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

* Python Version Running the Client:  Python 3.7.2
* OS running the TeamServer: Kali Linux
* Python version running the Teamserver:  3.7.2

## Expected Behavior

Hoping to start teamserver.

## Current Behavior

Unable to start teamserver.py

## Failure Information

Unable to start teamserver.py

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

(root) root@kali:~/SILENTTRINITY# python3 teamserver.py 192.168.8.10 test1234

### Failure Logs

Nothing more than what's provided above.

**Comment by byt3bl33d3r** [comment]
@chrisandjer949 did you follow the install instructions and use `pipenv` to install it? seems like you're just missing the `aiosqlite` dependency

**Comment by byt3bl33d3r** [comment]
Closing because of no response and plus I'm pretty sure my comment above was the problem.

**Comment by chrisandjer949** [comment]
Sorry for the silence.  Been out on travel.  Could be an issue with my Kali since I didn't see this issue in Ubuntu.  Will retry.  Thanks again!
