### ISSUE TITLE
Minidump module fails when sending the dump file

### ISSUE THREAD

**Issue by cyberfreaq** [byt3bl33d3r/SILENTTRINITY#117]
I tried using the boo/minidump module and the dumpfile gets written successfully to the specified directory on the client. However, when sending the dump file back to the server, I get the following error message when the final chunk is sent:
```[*] Sending chunk 227/230, bytes remaining: 280155
[*] Sending chunk 228/230, bytes remaining: 198235
[*] Sending chunk 229/230, bytes remaining: 116315
[*] Sending chunk 230/230, bytes remaining: 34395
[*] Sending FINAL chunk 231, bytes remaining: 0
[Channel: https CallbackUrl: 'https://10.1.1.3:443'] Error sending job results: The remote server returned an error: (400) Bad Request.
Error sending job (id: 9SLL4Gnfdo) results with https channel: Unable to perform SendJobResults() operation using callback URLs
```

Do you have any idea why this happens or how to troubleshoot the issue?

**Comment by byt3bl33d3r** [comment]
@cyberfreaq I've used this module a dozen times at this point and never had this issue.
I'm closing this issue cause you didn't fill out the required information needed in the bug report template and I'm going to need that in order to reproduce this.
Feel free to resubmit.
