### ISSUE TITLE
[BUG] teamserver.py file not found.

### ISSUE THREAD

**Issue by NotoriousRebel** [byt3bl33d3r/SILENTTRINITY#130]
# Issue Template

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
Just git cloned it trying to set it up and teamserver.py no longer exists

* SILENTTRINITY Version: Most recent 
* OS running the Client: Kali GNU/Linux Running
* Python Version Running the Client Python3.7.3
* OS running the TeamServer: Kali GNU/Linux Running
* Python version running the Teamserver: Python3.7.3

## Expected Behavior

Teamserver.py exists

## Current Behavior

What is the current behavior?
teamserver no longer exists

## Failure Information

Please help provide information about the failure if this is a bug.
See screenshot below
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
1. python3.7 teamserver.py ip password

### Failure Logs

Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/36310667/67454124-11733180-f5f7-11e9-8fa0-4a0eaf1a1746.png)

**Comment by NotoriousRebel** [comment]
It seems that teamserver.py got renamed; however, when I try to use it now I get
![image](https://user-images.githubusercontent.com/36310667/67454624-e558b000-f5f8-11e9-9a54-cfa1fbb7f19a.png)

**Comment by zqyves** [comment]
Not a bug. The method to call the teamserver got changed. 

`Usage: st [-h] [-v] (client|teamserver) [<args>...]
options:
    -h, --help                   Show this help message and exit
    -v, --version                Show version`

so python3 st.py teamserver <IP> <pass>

**Comment by byt3bl33d3r** [comment]
I will update the documentation when I get a sec (at WWHF now). See @zqyves's answer.
