### ISSUE TITLE
How to create user?

### ISSUE THREAD

**Issue by ioscanner** [byt3bl33d3r/SILENTTRINITY#138]
I can't find the documentation of how to create users on the teamservers of a new install.  It seems the client now requires wss://user:pass@host:5000 . But no details on how to create the users are present on site or docs.

Thanks in advance
IO

**Comment by byt3bl33d3r** [comment]
There's no need to crate a user on the teamserver. You just specify a username in the connection URL string. If the password is correct and there isn't another user logged in with the same username you'll be good to go. (e.g. how Cobalt Strike does it.)

Cheers
