### ISSUE TITLE
[FEATUREREQUEST] Redirector Support

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [byt3bl33d3r/SILENTTRINITY#139]
## Expected Behavior

Run Silenttrinity behind redirector/proxy.

## Current Behavior

BindIP can be set to 0.0.0.0 but there is no option for staged payloads to specify the redirector URL/Domain/IP. 

## Failure Information

Staged Payloads try to connect to 0.0.0.0. Only stageless payloads work here.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run Silenttrinity behind a redirector
2. Set BindIP to 0.0.0.0 or the Internet Facing IP
3. No way to specify the Redirector Domain/URL for staged payloads

**Comment by glides** [comment]
Set the “CallBackURLs” value before starting your listener. CallBackURLs can be hostnames or IPs

**Comment by glides** [comment]
![image](https://user-images.githubusercontent.com/3959147/73454011-346e5980-433b-11ea-95cc-c6ffda8cf079.png)

**Comment by S3cur3Th1sSh1t** [comment]
Ah, okay thats my fault. I was looking for it in the stagers menu. Closed.
