### ISSUE TITLE
Cannot use staged payloads (only stageless) [BUG]

### ISSUE THREAD

**Issue by delta-plus** [byt3bl33d3r/SILENTTRINITY#147]
# Cannot use staged payloads (only stageless)

## Context

* SILENTTRINITY Version: 0.4.6dev (from latest Ubuntu release in Actions)
* OS running the Client: Kali
* Python Version Running the Client: 3.7
* OS running the TeamServer: Kali
* Python version running the Teamserver: 3.7

Note: The powershell_stageless payload works perfectly and is flawlessly stealthy, despite being PowerShell. Seriously, well done, man. Your code is legend. If this issue is on my end, I apologize for wasting your time.

## Expected Behavior

Payloads such as msbuild, powershell, and wmic should download and compile stage code...

## Current Behavior

...but they don't. Execution happens and calls back to the server. The stage is sent, but can't compile. I've only tested this on the latest Windows 10.

## Failure Information

Here's what the error looks like from the Windows command prompt of the target:
```
[-] Attempt #1
[*] Downloaded 569104 bytes

[*] Compiling Stage Code
[-] Error(s) compiling script, this probably means your Boo script has bugs

Stage.boo(146,35): BCE0022: Cannot convert 'Boo.Lang.List' to 'Boo.Lang.List'.
Stage.boo(570,27): BCE0022: Cannot convert 'Boo.Lang.List' to 'Boo.Lang.List'.
Stage.boo(571,31): BCE0022: Cannot convert 'Boo.Lang.List' to 'Boo.Lang.List'.
```
It repeats like this until you kill the prompt.

### Steps to Reproduce

1. Download latest Ubuntu binary from the Actions tab.
2. Fire up Silent Trinity and start an https listener.
3. Generate some non-powershell_stageless stager.
4. Execute stager on Windows 10 target.

**Comment by kaftejiman** [comment]
The fix would be removing the explicit type casting in the mentioned lines:

```
in silenttrinity/core/teamserver/data/stage.boo change:
    public Jobs as List = []
    public Channels as List = [PUT_COMM_CLASSES_HERE]
to simply:
    public Jobs = []
    public Channels = [PUT_COMM_CLASSES_HERE]
```
```

in silenttrinity/core/teamserver/comms/http.boo and https.boo change:
    public CallBackUrls as List = []
to simply:
    public CallBackUrls = []
```

**Comment by delta-plus** [comment]
Yeah, that should do the trick. Thanks a bunch!

**Comment by unKn0wnUser453** [comment]
I am still having this same problem.... I don't think these were ever committed...
in silenttrinity/core/teamserver/data/stage.boo change:
    public Jobs as List = []
    public Channels as List = [PUT_COMM_CLASSES_HERE]
to:
    public Jobs = []
    public Channels = [PUT_COMM_CLASSES_HERE]

in silenttrinity/core/teamserver/comms/http.boo and https.boo change:
    public CallBackUrls as List = []
to:
    public CallBackUrls = []

Would send the stage forever ... made the change ... got a session! :D

**Comment by AFBishop** [comment]
I am still having this same problem.... I don't think these were ever committed...

**Comment by podjackel** [comment]
Just confirmed same issue still present.
