### ISSUE TITLE
[BUG] Client crashes after using any command

### ISSUE THREAD

**Issue by yukiryqqe** [byt3bl33d3r/SILENTTRINITY#172]
* SILENTTRINITY Version: 0.4.6
* OS running the Client: Kali Linux 2023.1
* Python Version Running the Client: 3.11.2
* OS running the TeamServer: Kali linux 2023.1
* Python version running the Teamserver: 3.11.2

After successfully starting teamserver, I start client and then after entering any command it says 'Press ENTER to continue' and stops responding

[0] ST ≫ help
Press ENTER to continue
help
help

**Comment by vlados31999** [comment]
I have the same situation
