### ISSUE TITLE
Ability to rename agent

### ISSUE THREAD

**Issue by iNoSec** [byt3bl33d3r/SILENTTRINITY#18]
Like the title say i just want to ask if it is possible to implement renaming the agent after he pop upp like in Empire?!
Thanks for the amazing work and like i already said on twitter you are an amazing coder and pentester, one of the best!!! and all your github prove it!!!

**Comment by davidtavarez** [comment]
That's something I was thinking... here's the PR https://github.com/byt3bl33d3r/SILENTTRINITY/pull/19

**Comment by byt3bl33d3r** [comment]
I think he means renaming the agent UUID rather than the stager filename. That's on the priority list.

Thanks for the compliments :) 

Cheers

**Comment by iNoSec** [comment]
Yeah thats what i mean. Thanks for the good job

**Comment by davidtavarez** [comment]
You mean like this https://github.com/byt3bl33d3r/SILENTTRINITY/pull/21 ?

**Comment by iNoSec** [comment]
Thanks guys !!!change your name with lucky luke😁
