### ISSUE TITLE
ZIP Encryption

### ISSUE THREAD

**Issue by b2az** [byt3bl33d3r/SILENTTRINITY#25]
Holla at you dudettes,

First of all, big **thank you** for your great work on the readme.md - helped me to understand all of this in a couple of minutes.

I got a feature-request on the zip-file exchaning:
In my opinion it would make sense, that the zip-blob is being encrypted server-sidely before sending it to the C#-agent.
If the ZIP-file is fetched by a sandbox or by an analyst, it is useless without the key, which is maybe implemented in the binary.

Hope i can contribute to this project in the near future 👍

**Comment by byt3bl33d3r** [comment]
Unfortunately the native C# ZIP library does not support encryption. I'd have to use a third party assembly which is definitely possible but would make the actual C# stage much bigger.
I do agree this would be ideal, will keep it open as a reminder

**Comment by byt3bl33d3r** [comment]
@b2az this has been taken care of in the `c2_crypto` branch, all the comms are now encrypted using ECDHE, including the zip stage :) 

Closing
