### ISSUE TITLE
fail to pip install  requirements.txt

### ISSUE THREAD

**Issue by gearcapitan** [byt3bl33d3r/SILENTTRINITY#37]
![kali_linux-2019-01-23-23-35-38](https://user-images.githubusercontent.com/13740942/51656788-0d32be80-1f68-11e9-95c9-48169b0bd5b0.png)

**Comment by daddycocoaman** [comment]
Incorrect pip syntax.

`pip3.7 install -r requirements.txt`

**Comment by True-Demon** [comment]
I strongly recommed using `pipenv install` instead to install the virtual environment. This thing is still under heavy development, and though I trust byt3bl33d3r will try to avoid breaking changes, this will make sure you keep all your dependencies intact separate from your global pip installations.

**Comment by byt3bl33d3r** [comment]
> Incorrect pip syntax.
> `pip3.7 install -r requirements.txt`

This is the correct answer, and also yes I strongly recommend using pipenv as it simplifies this a lot.
