### ISSUE TITLE
Update Mimikatz

### ISSUE THREAD

**Issue by eksperience** [byt3bl33d3r/SILENTTRINITY#40]
Hey there!
Is it possible to update Mimikatz to version 2.1.1-20181209?
Thanks in advance!

**Comment by egypt** [comment]
It would also be nice if all the modules that use compiled DLLs could load them dynamically so users could more easily replace with their own custom compiled versions.

**Comment by byt3bl33d3r** [comment]
awesome idea, I'll open a new issue with this so i remember
