### ISSUE TITLE
st.py crashes when typing an invalid option

### ISSUE THREAD

**Issue by n00py** [byt3bl33d3r/SILENTTRINITY#44]
## Context

When trying to navigate through the CLI, typing an invalid option causes the CLI to crash.  

* SILENTTRINITY Version: 0.0.1dev
* Operating System: Kali Linux 2.0
* Python Version: 3.7

## Expected Behavior

Either going to the modules menu or the application giving an error message.

## Current Behavior

Python crashes.

## Failure Information

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce
`ST (modules)(ipconfig) ≫ modules     `                                                                                                                                    
`ST (modules)(ipconfig) ≫ sessions   `                                                                                                                                     
`ST (sessions) ≫ sessions modules    `                                                                                                                                     
`Traceback (most recent call last):`
`  File "st.py", line 143, in <module>`
`    loop()`
`  File "st.py", line 120, in __call__`
`    self.parse_result(result)`
`  File "st.py", line 94, in parse_result`
`    bound_cmd_handler = functools.partial(getattr(self.current_context, command[0]), ``args=command[1:])`
`TypeError: the first argument must be callable`

![image](https://user-images.githubusercontent.com/14309124/52737287-348a1380-2f89-11e9-871c-03f58123713f.png)

**Comment by byt3bl33d3r** [comment]
@n00py this has been fixed in the `c2_crypto` branch that contains the 0.1.0 update. I'll be merging into master tomorrow
