### ISSUE TITLE
Windows 10 Defender (March 4, 2019 update) appeared to blocked msbuild.xml executing

### ISSUE THREAD

**Issue by chrisandjer949** [byt3bl33d3r/SILENTTRINITY#49]
# Issue Template

## Context

I fired up my Windows 10 test VM just now and received an update for Defender Virus & Threat setting (march 4. 2019).   Launched the msbuild.xml file and Defender popped a Threat Notification.   2 days ago, Defender did not catch it... yet.

Behavior:  Win32/Quiltan.A!sms
Recommended action:  Quarantine threat now.

* SILENTTRINITY Version: 0.1.0dev
* Operating System: Kali Linux 2018
* Python Version: 3.7.2

## Expected Behavior

Windows Defender as of March 4, 2019 is picking up msbuild.xml being executed.  Renaming the msbuild.xml file did not change anything.

## Current Behavior

Defender is blocking backdoor connection back to Kali Silenttrinity.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Get latest Windows Defender definition update for March 4, 2019.
2. Try to execute C:\.....\msbuild.exe  msbuild.xml
3. Defender popped up a threat notification.
   ...

### Failure Logs

Please include any relevant log snippets or files here. Try using: `python3.7 st.py -d` to get more information.

**Comment by davidtavarez** [comment]
Thank you for reporting this.

**Comment by chrisandjer949** [comment]
One behavior I noticed is if ST is already running with a connection to the victim PC and then enable Defender, nothing is blocked.  ST still works.  Looks like Defender is just looking at the initial connection stage.

**Comment by byt3bl33d3r** [comment]
This is not a bug.  This was bound to happen sooner or later as this is one of the pitfalls of open sourcing a tool like this. Everything that can be signatured will be signatured (just like Metasploit and Empire). 

I guarantee that if you recompile the C# stager and change the msbuild file template a bit it will get by. 
I'm definitely ***not*** interested in dealing with the ol' cat and mouse game with ST, however anybody is more than welcome to update the templates and submit the changes as a PR.
