### ISSUE TITLE
Log actions and results

### ISSUE THREAD

**Issue by maaaaz** [byt3bl33d3r/SILENTTRINITY#53]
Hello @byt3bl33d3r,
It would be cool if all the actions and results could be logged, just like the `spool` command with metasploit.

Cheers dude !

EDIT : I see that this feature is already possible but not enabled, a user option is more than welcome
https://github.com/byt3bl33d3r/SILENTTRINITY/blob/907eee2b6755515769bd4314eb11d267390e0a32/Server/st.py#L154

**Comment by byt3bl33d3r** [comment]
Just implemented!
Thanks!
