### ISSUE TITLE
Crashed when looking for help on sessions

### ISSUE THREAD

**Issue by ad0nis** [byt3bl33d3r/SILENTTRINITY#59]
## Context

* SILENTTRINITY Version: 0.1.0dev
* Operating System: Kali 2019.1
* Python Version: 3.7.3rc1

## Expected Behavior

Expected help on sessions, or an error about a non-existent option...

## Current Behavior

st.py server crashed when running 'sessions -h'

### Steps to Reproduce

1. Start https listener
2. Generate powershell payload
3. create session
4. Run sessions -h from sessions menu

### Failure Logs

ST (sessions) ≫ sessions -h                                                                                       
Traceback (most recent call last):
  File "st.py", line 163, in <module>
    loop()
  File "st.py", line 140, in __call__
    self.parse_result(result)
  File "st.py", line 95, in parse_result
    bound_cmd_handler = functools.partial(getattr(self.current_context, command[0]), args=command[1:])
TypeError: the first argument must be callable

**Comment by byt3bl33d3r** [comment]
Fixed.

Cheers
