### ISSUE TITLE
Stager SSL cipher errors on Windows 8.1 embedded industry pro 

### ISSUE THREAD

**Issue by RayofLightz** [byt3bl33d3r/SILENTTRINITY#6]
In the description it says that .NET 4.5 is needed to run the stagger and the payloads. The python web server throws a "no shared cipher" error. Is this something odd to do with windows 8.1 embedded ? I am going to throw a Console.WriteLine in the inline c# stagger and  see if I can get any other info.

**Comment by byt3bl33d3r** [comment]
I'm pretty sure that's because .NET 4.5 isn't installed on windows 8.1 embedded by default. Only .NET 4.5 supports the newest TLS ciphers that ST uses.

Feel free to do some debugging tho.

**Comment by davidtavarez** [comment]
Could you give more details? How did you generate the stager? How did you run it? Can you give more information about the Windows machine? What shows you when you execute: `systeminfo | findstr /C:"OS"`?

Thanks.

**Comment by RayofLightz** [comment]
The `systeminfo | findstr "OS"` gives me `6.3.9.96000 N/A Build 96000`

**Comment by RayofLightz** [comment]
Is their anyway I could get the deobfuscated c# build source code?  The windows box I am using is just for hopefully contributing to this project so I could always manually install the newest version of the dot net framework, but if I could hack together a stagger that would work for both windows 10 and 8.1...

**Comment by yaap7** [comment]
Same issue here with 2012 R2 Standard (6.3.9600) and .NET Framework version 4.0.30319.42000.

In `Server/listeners/http.py`, line 66:
``` python
ssl_context.set_ciphers('ECDHE+AESGCM')
```
I just commented out this line and the stager was able to connect.

In my opinion, the ciphers used in ST are too restrictive (which is a good point for security) but in this context I think we could be more lax.
What do you think about configuring a more permissive set of ciphers?

**Comment by MikeLim7** [comment]
Agree with @yaap7, only Windows 10 and Server 2016 supports ECDHE+AESGCM.  Win8.1, Server 2012 R2 and older Windows versions  support ECDHE+AES.  Besides commenting out, another alternative is probably set_ciphers('ECHDE+AESGCM:ECDH+AES'). 

 Full cipher list at https://docs.microsoft.com/en-us/windows/desktop/secauthn/cipher-suites-in-schannel

**Comment by byt3bl33d3r** [comment]
This should have been fixed in the `c2_crypto` branch, feel free to try it out and report back :)

**Comment by byt3bl33d3r** [comment]
This was fixed in 69530ae79e9a7e6b24f6a9bf6fadb5c7e57b81c2
