### ISSUE TITLE
Detect Proxy Credentials From System

### ISSUE THREAD

**Issue by dipanshu1993** [byt3bl33d3r/SILENTTRINITY#60]
# Issue Template

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* SILENTTRINITY Version:
* Operating System:
* Python Version:

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Information

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. step 3
   ...

### Failure Logs

Please include any relevant log snippets or files here. Try using: `python3.7 st.py -d` to get more information.

**Comment by dipanshu1993** [comment]
The current version of SILENTTRINITY unable to detect proxy credentials from the system while initiating a connection to the attacker's machine. 

In one of the scenarios, we have created the msbuild.xml payload and send it to the victim. Once the victim executes the payload, it through error as below:
"Error sending job results to http://122.23.43.1/c3234: The remote server returned an error: (407) Proxy authentication required.

**Comment by byt3bl33d3r** [comment]
Can you try this again with the latest update? 
Thanks

**Comment by byt3bl33d3r** [comment]
This should be fixed as per https://github.com/byt3bl33d3r/Naga/commit/160e6bbbc1aceb05896e71e717aa0b68ac49a681
