### ISSUE TITLE
Automatically attempt to elevate permissions or add Get SYSTEM module

### ISSUE THREAD

**Issue by kildonan5** [byt3bl33d3r/SILENTTRINITY#65]
## Context
* SILENTTRINITY Version: 0.1.0dev
* Operating System: Kali 2019.2
* Python Version: Python 3.7.3rc1

## ST Setup & resulting behavior
HTTPS Listener on 8080
MSBuild stager executed on Windows Server 2016 client, under the context of a domain user in the local administrators group
Module = ipy/mimikatz
run all

Output:
    
    [+] f83a38c9-14fe-44ad-870f-2d70fc3e24e7 returned job result (id: LJpKMPve)
    [-] Not in high integrity process

## Expected Behavior
ST Should attempt to elevate privileges to system, before running the Mimikatz and/or any LSASS related modules. Alternatively create a separate module (such as MSF 'get system') which would achieve this purpose.

## Current Behavior

Even if the session is running under the context of a user in the administrators group, LSASS modules, fail to execute (dump memory).

**Comment by kozlovsas** [comment]
Definitely would love to see an elevation of privilege module (via Process Injection, Token Impersonation, etc).

If there's any way I can assist I'd love to help out (testing, writing the modules)

**Comment by byt3bl33d3r** [comment]
This was added in the newest update. Some changes are going to be needed to make it a bit more streamlined but the code is there.
Cheers

**Comment by kildonan5** [comment]
When you say this was added, do you mean a getsystem module/feature? I have not had a chance to test it again (im having trouble building it from source) but watched your webinar, and when it came to dump creds, I saw you spawned a new session using a specific payload (winrm?), instead of elevating or running any sort of getsystem functionality.
