### ISSUE TITLE
Shell module - Special Character handling

### ISSUE THREAD

**Issue by kildonan5** [byt3bl33d3r/SILENTTRINITY#67]
It seems ST is unforgiving and particular when it comes to special characters in the shell module command option. For instance in order to successfully get a directory listing of C:\ Your command must be "dir C:\\\\" or it won't work. Furthermore, I have yet figured out how to handle spaces, so I can list the contents of something like "C:\Program Files" (I tried escaping the space with a backslash, two backslashes, quotation marks around the whole thing, escaping those quotation marks, etc etc).

Ultimately it would be nice if the end user didn't have to figure out proper escaping. For instance;

set Command dir "C:\Program Files\"

If thats not possible, due to how you are processing module parameters, then maybe the next best thing is to include proper escaping techniques in the "Command" option description (listed when you type "options".

## Context
* SILENTTRINITY Version: 0.1.0dev
* Operating System: Kali 2019.2
* Python Version: Python 3.7.3rc1

## ST Setup & resulting behavior
HTTPS Listener on 8080
MSBuild stager executed on Windows Server 2016 client
Module = ipy/shell

**Comment by byt3bl33d3r** [comment]
Closing in favor of #88
