### ISSUE TITLE
safetykatz.py output folder

### ISSUE THREAD

**Issue by T3KX** [byt3bl33d3r/SILENTTRINITY#7]
Hey byt3bl33d3r,

big fan of your work,

I notice in /module/src/safetykatz.py

the output folder destination " {0}\\Temp\\debug.bin "got block by default on my windows10 

i change it to  : 
    dumpFile = "{0}\\system32\\spool\\drivers\\color\\debug.bin".format(systemRoot)

And it work , continue the good work !!

**Comment by byt3bl33d3r** [comment]
All add an option to the module to specify the memory dump location. Thanks for the info!

**Comment by byt3bl33d3r** [comment]
Fixed in #9
