### ISSUE TITLE
Error with :  IPY stdlib in embedded resources

### ISSUE THREAD

**Issue by idlewog** [byt3bl33d3r/SILENTTRINITY#72]
# Issue Template

## Context

Doing test with ST

* SILENTTRINITY Version: last one
* Operating System: kali linux full update / windows 10 full update
* Python Version: 3.7

## Failure Information
Everything run fine ... until i got this (windows side)

PS C:\Users\ddd\Documents> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe msbuild.xml
Microsoft (R) Build Engine, version 4.7.3056.0
[Microsoft .NET Framework, Version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. Tous droits réservés.

La génération a démarré 01/08/2019 16:56:07.
URL: http://xxxx/fcc70e90-bef1-4e8a-8348-9e2bbd1b6f60

Trying to resolve assemblies by staging zip
Attempting HTTP POST to http://xxxx/fcc70e90-bef1-4e8a-8348-9e2bbd1b6f60
Attempting HTTP GET to http://xxxx/fcc70e90-bef1-4e8a-8348-9e2bbd1b6f60
Downloaded 1950224 bytes
Found Microsoft.Scripting.dll in zip
'Microsoft.Scripting, Version=1.2.2.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Found IronPython.dll in zip
'IronPython, Version=2.7.9.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Found Microsoft.Dynamic.dll in zip
'Microsoft.Dynamic, Version=1.2.2.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
Found IronPython.Modules.dll in zip
'IronPython.Modules, Version=2.7.9.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1' loaded
**Did not find IPY stdlib in embedded resources: La séquence ne contient aucun élément.**
Found IronPython.dll in zip
Found Main.py in zip

And then no session is created on ST

i apologize if it's my fault because i miss something ... but i can't figure out what by now

thanks

**Comment by byt3bl33d3r** [comment]
This should be fixed now.
Thanks
