### ISSUE TITLE
[BUG] Listener http doesn't open port

### ISSUE THREAD

**Issue by looCiprian** [byt3bl33d3r/SILENTTRINITY#74]
## Context 
Setup:
* SILENTTRINITY Version: 0.3.0dev
* OS running the Client: kali 4.19.0-kali3-amd64
* Python Version Running the Client: Python 3.7.3rc1
* OS running the TeamServer: kali 4.19.0-kali3-amd64
* Python version running the Teamserver: Python 3.7.3rc1

## Expected Behavior

The listener should open the port configured in the "listerners/http" set up.

## Current Behavior

After setting up the listener and started it doesn't open the port and the target host cannot reach the listener handler

## Failure Information
Starting the listener (Debug info from the teamserver):
```
2019-08-17 16:38:02,073 3296 MainThread - [DEBUG] protocol.py: write_frame - server > 
Frame(fin=True, opcode=1, data=b'{"type": "message",
"id": "wfH3LrCwSx",
"ctx": "listeners",
"name": "list",
"status": "success",
"result": {"http": {"name": "http",
"author": "@byt3bl33d3r",
"description": "HTTP listener",
"running": true,
"options": {"Name": {"Description": "Name for the listener.",
"Required": true,
"Value": "listen_http"},
"BindIP": {"Description": "The IPv4/IPv6 address to bind to.",
"Required": true,
"Value": "10.0.2.15"},
"Port": {"Description": "Port for the listener.",
"Required": true,
"Value": "8123"},
"Comms": {"Description": "C2 Comms to use",
"Required": true,
"Value": "http"}}}}}', rsv1=False, rsv2=False, rsv3=False)
```
Stopping the listener (Debug info from the teamserver):
```
2019-08-17 16:39:40,705 3296 MainThread - [DEBUG] protocol.py: write_frame - server > 
Frame(fin=True, opcode=1, data=b'{"type": "message",
"id": "RyPmvQyfgV",
"ctx": "listeners",
"name": "stop",
"status": "success",
"result": null}', rsv1=False, rsv2=False, rsv3=False)
```

### Steps to Reproduce

1. ```python3 st.py wss://username:test@127.0.0.1:5000```
2. ```listeners```
3. ```use http```
4. ```set Port 8123```
5. ```start```
6. ```list```

### Failure Logs
Starting the teamserver:
<img width="1402" alt="Screenshot 2019-08-17 at 22 29 20" src="https://user-images.githubusercontent.com/30753137/63217118-7d8d7100-c140-11e9-805d-122e0cc5bc8e.png">

Starting the client:
<img width="1402" alt="Screenshot 2019-08-17 at 22 30 59" src="https://user-images.githubusercontent.com/30753137/63217119-7fefcb00-c140-11e9-9da9-ac63657a8417.png">

# Thx, awesome project

**Comment by jsarkisian** [comment]
Same exact issue... port won't open. Firing the stager tries to connect back about 10 times and then errors out. Thanks!

**Comment by byt3bl33d3r** [comment]
This will be fixed an an upcoming update.

Thanks
