### ISSUE TITLE
Error in retrieving the stager

### ISSUE THREAD

**Issue by msidagni** [byt3bl33d3r/SILENTTRINITY#8]
I set up Silent Trinity on Kali and retrieved all the requirements with pip. Launched st.py with python3 successfully.

Set up a listener and a stager using msbuild. Transferred the msbuild.xml to target box and launched it with MSbuild.exe

I get the error:

Error downloading https://<IP>/stage.zip: The underlying connection was closed: An unexpected error occurred on a send.

It seems not to be able to get the stager and the Windows box is in the same network as the listener box.

**Comment by davidtavarez** [comment]
can you double check the URL? try to use `stvenom.py` (https://github.com/byt3bl33d3r/SILENTTRINITY/wiki/Generating-stagers) and read the `.res` file to verify the URL. Also, msbuild.xml should have the URL.

**Comment by msidagni** [comment]
Generated the stagers with stvenom.py per the wiki. Generated msbuild.xml and verified URL in it and the server launched correctly on the IP:port. Still the same error. It looks like it cannot find the stage.zip

**Comment by msidagni** [comment]
When I try to hit the URL from the target Windows host directly with a browser:

https://<IP>:8089/stage.zip

It shows this error:

Internal Server Error
Server got itself in trouble

**Comment by davidtavarez** [comment]
try to enable the debug mode:

```
python3.7 st.py -d    
```

**Comment by msidagni** [comment]
Enabled the debug mode of the server:

this is error I get on the server

File "listeners/http.py", line 120, in stage
    with ZipFile(stage_file, 'a', compression=ZIP_DEFLATED, compresslevel=9) as zip_file:
TypeError: __init__() got an unexpected keyword argument 'compresslevel'

**Comment by davidtavarez** [comment]
You're not running python3.7

`compresslevel` was added on python 3.7 https://docs.python.org/3.7/library/zipfile.html

**Comment by davidtavarez** [comment]
Try with this short guide: https://github.com/byt3bl33d3r/SILENTTRINITY/wiki/Setting-up-your-development-environment

**Comment by msidagni** [comment]
On Kali, installed Python 3.7. It gives a weird SSL cipher error. By deleting that compression statement, it works on standard python3

**Comment by Martinerw** [comment]
I have the same error. Msidagni can you be more specific how do you solve the problem.

**Comment by davidtavarez** [comment]
Please use this template to report issues [Issue-Templae](https://github.com/byt3bl33d3r/SILENTTRINITY/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by T3KX** [comment]
Hi msidagni , what is your victim OS ?

**Comment by iNoSec** [comment]
just use python3.7 and thats work!!! i have the same issue and when i see the requirements for silenttirnity works only with 3.7 and i tired with 3.6...

**Comment by davidtavarez** [comment]
Should be this issue closed?
